### ISSUE TITLE
Add React frontend

### ISSUE THREAD

**Issue by andrew-gardener** [tl-its-umich-edu/my-learning-analytics#417]
- [x] add initial React+Webpack+Django plumbing (~#420~)
- [X] switch over grade distribution dashboard (~#421~)
- [X] switch over assignment planning dashboard (#422)
- [X] switch over files accessed dashboard (#423)
- [X] switch over sign in page, in progress here: https://github.com/tl-its-umich-edu/my-learning-analytics/pull/515 (#424)
- [x] disable views on front end that are disabled on back end (~#469~)
- [x] switch over course index page (~#429~)
- [ ] api endpoint modifications/additions (#425)
  - [x] modified `grade_distribution` endpoint to work with course id (not incremented course id)
  - [ ] add user endpoints to get `current_user` info
- [ ] frontend tests (#426)
- [ ] remove old front end dependencies (angularjs, older version of d3, etc) (#427)

**Comment by justin0022** [comment]
@andrew-gardener could you set up a `user` endpoint that takes some student identifier and returns name and the course ids that they are enrolled in?
