### ISSUE TITLE
Show submitted assignments as well as graded assignments in Assignment Planning

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#976]
## Describe your problem or feature you'd like added
Feedback from students has indicated that they want visual confirmation that an assignment has been submitted.  Currently, the Assignment Planning view only shows visual differences between assignments that are graded or ungraded.

## Describe the solution you'd like
Visually differentiate between assignments:
- Unsubmitted
- Submitted and ungraded
- Graded

## Tasks

- [x] add info color to default palette
- [x] add migration file for adding submitted_at field
- [x] update the assignment planning view to show submitted but not graded submissions
- [x] update the SQL dump file on Google Drive (new dump file added as [myla_test_data_2020_06_29.sql](https://drive.google.com/drive/u/0/folders/1Pj7roNjRPGyumKKal8-h5E6ukUiXTDI9))

**Comment by zqian** [comment]
@ssciolla I will attach some screenshots here. Thanks for reviewing.

**Comment by jennlove-um** [comment]
Testing passes: Assignments that have a submitted date but no graded date display as pending grades.  

There was a question about some data not getting into the MyLA data base for submissions that Zhen is looking into, but when the data is there, this works correctly.
